# -*- coding: utf-8 -*-
# Deployment settings for ChefTeam.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.1/s3e/makefile_builder/mkb.py', 'c:/Users/Zachary/Documents/ChefTeam/ChefTeam.mkb', '--deploy-only', '--hub-data', 'C:/Users/Zachary/Documents/ChefTeam/project_ChefTeam/mkb-windows.txt', '--buildenv=VC11X']
mkb = 'c:/Users/Zachary/Documents/ChefTeam/ChefTeam.mkb'
mkf = ['c:\\marmalade\\7.1\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.1\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.1\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.1\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.1\\modules\\iwnui\\iwnui.mkf', 'c:\\marmalade\\7.1\\extensions\\s3enui\\s3enui.mkf', 'c:\\marmalade\\7.1\\extensions\\s3enui\\s3enui_iwui.mkf', 'c:\\marmalade\\7.1\\modules\\iwui\\iwui.mkf', 'c:\\marmalade\\7.1\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.1\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.1\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.1\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.1\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.1\\modules\\third_party\\tiniconv\\tiniconv.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Zachary/Documents/ChefTeam/data/iwui_style/fonts/FreeMono.ttf', 'iwui_style/fonts/FreeMono.ttf', 0),
    ('c:/Users/Zachary/Documents/ChefTeam/data/iwui_style/fonts/FreeSans.ttf', 'iwui_style/fonts/FreeSans.ttf', 0),
    ('c:/Users/Zachary/Documents/ChefTeam/data/iwui_style/fonts/FreeSerif.ttf', 'iwui_style/fonts/FreeSerif.ttf', 0),
    ('c:/Users/Zachary/Documents/ChefTeam/data-ram/data-gles1/iwui_style/iwui_style.group.bin,c:/Users/Zachary/Documents/ChefTeam/data/iwui_style/iwui_style.group.bin', 'iwui_style/iwui_style.group.bin', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'ChefTeam'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'ChefTeam'
    long_caption = 'ChefTeam'
    version = [0, 0, 1]
    config = ['c:/Users/Zachary/Documents/ChefTeam\\data\\app.icf']
    data_dir = 'c:/Users/Zachary/Documents/ChefTeam/data'
    iphone_link_lib = ['s3eNUI ']
    wp8_ext_managed_dll = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = ['c:/marmalade/7.1/extensions/s3enui/lib/iphone']
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = ['c:/marmalade/7.1/extensions/s3enui/lib/android/s3eNUI.jar']
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    wp8_ext_native_dll = []
    win32_ext_dll = []
    android_so = ['c:/marmalade/7.1/extensions/s3enui/lib/android/libs3eNUI.so']
    osx_ext_dll = []
    tizen_so = []
    wp8_ext_capabilities = []
    iphone_link_libs = []
    iphone_app_fonts = 1
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_x86/ChefTeam.so',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_x86/ChefTeam.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_x86_tizen/ChefTeam.s86',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_x86_tizen/ChefTeam.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_mips/ChefTeam.so',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_mips/ChefTeam.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_arm/ChefTeam.s3e',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_arm/ChefTeam.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_mips/ChefTeam.so',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_mips/ChefTeam.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_gcc_x86_android/ChefTeam.so',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_gcc_x86_android/ChefTeam.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_arm/ChefTeam.s3e',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_arm/ChefTeam.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Debug_ChefTeam_VC11X_x86/ChefTeam.s86',
                   'release' : r'c:/Users/Zachary/Documents/ChefTeam/build_chefteam_vc11x/Release_ChefTeam_VC11X_x86/ChefTeam.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
